### ISSUE TITLE
기획 완성

### ISSUE THREAD

**Issue by Dongjun-Jii** [Team-QSS/NoDoubt#1]
경민이가 위키에 추가바람
다음주 금요일까지

있어야 할 것들
1. 게임 컨셉 및 특징
2. 게임 규칙 혹은 플레이 방식
3. 게임 플랫폼
4. 게임 화면 구성
5. 디자인 컨셉트
6. 스토리 및 세계관(있다면)
또 뭔가 있으면 추가좀

**Comment by Dongjun-Jii** [comment]
https://gist.github.com/ihoneymon/652be052a0727ad59601
https://github.com/Hunnywind/BigGuild/wiki/%EB%AC%B8%EB%B2%95
위키문법이다. 참고ㄱㄱ

**Comment by usernameSplash** [comment]
노답 기획 작성 시작

**Comment by usernameSplash** [comment]
4번, 6번 항목 제외하고 작성 완료
노답에 세계관도 넣을까? 넣기 힘들 것 같긴 한데

**Comment by Dongjun-Jii** [comment]
없다면 생략해도 됨

**Comment by Dongjun-Jii** [comment]
그냥 게임에 모든것을 적는거 뿐이니까

**Comment by usernameSplash** [comment]
인게임 맵 그렸으니 확인바람
아이템 관련 세부기획이나 인게임에서 한 화면 안에 보이는 요소들은 추후 공지할게
아마 배경은 초원 텍스처vs 우주 텍스처 중에서 초원으로 굳어진 듯

**Comment by usernameSplash** [comment]
지금 2.5D로 할까 고민하고 있긴 한데... 2D로 할까 2.5D로 할까??

**Comment by usernameSplash** [comment]
ㅁㄴㅇㄹ 여기 레포지토리 생존신고하러 옴

**Comment by usernameSplash** [comment]
대회 끝나는대로 아이템목록 생각해올게
